//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoingToWorkApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDate
    {
        public int WorkDateId { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> WorkStart { get; set; }
        public Nullable<System.DateTime> BreakStart { get; set; }
        public Nullable<System.DateTime> BreakEnd { get; set; }
        public Nullable<System.DateTime> WorkEnd { get; set; }
    
        public virtual WorkDate WorkDate1 { get; set; }
        public virtual WorkDate WorkDate2 { get; set; }
    }
}
